name: Build runner image

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: write

env:
    imageName: ubuntu-machine
    arch: "linux/arm64"

jobs:
  build:
    concurrency:
      group: action-runner-${{ github.ref_name }}-build
      cancel-in-progress: true
    runs-on:
      group: permanent-runners
      labels:
        - macOS
        - mac-4
    steps:
        - name: Checkout repository
          uses: actions/checkout@v6

        - name: Setup container CLI
          run: |
            brew install container
            printf 'y\n' | container system start

        - name: Lås opp nøkkelring
          run: security -v unlock-keychain -p ${{secrets.MACOS_KC_PASS}} ~/Library/Keychains/login.keychain-db

        - name: Registry logins for container CLI
          run: |
            echo ${{ secrets.GITHUB_TOKEN }} | container registry login ghcr.io -u ${{ github.actor }} --password-stdin
            echo ${{ secrets.DOCKER_TOKEN }} | container registry login docker.io -u ${{ vars.DOCKER_USER }} --password-stdin

        - name: Build image
          run: |
            container build --platform ${{ env.arch }} -t local/${{ env.imageName }} -f ${{ env.imageName }}.Dockerfile .
        - name: Tag image
          run: |
            container image tag local/${{ env.imageName }}:latest ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]'):${{ env.imageName }}
        - name: Push image
          run: |
            container image push ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]'):${{ env.imageName }}
        - name: Prune images
          if: always()
          run: |
            container image prune --all
            container registry logout ghcr.io
            container registry logout docker.io