name: Runner maintenance

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Sets a schedule for executing the jobs
  schedule:
    - cron: "10 20 * * 2,4"

jobs:

  macos-maintenance:
    # Sets a matrix of labels on which to run the scripts
    strategy:
      matrix:
        runner:
          - mac-1
          - mac-2
          - mac-3
          - mac-4
    # The job will run in parallel for each of the runner labels listed above
    runs-on:
      - docker
      - self-hosted
      - ${{ matrix.runner }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Docker cleanup
        run: docker system prune -fa
      - name: Runner upgrades
        run: |
          brew bundle --file Brewfile --no-lock
          brew upgrade
