# This is a basic workflow to help you get started with Actions

name: Runner maintenance

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        runner:
          - mac-1
          - mac-2
          - mac-3
          - mac-4
    # The type of runner that the job will run on
    runs-on: 
      - self-hosted
      - ${{ matrix.runner }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Docker cleanup
        run: |
          docker system prune -fa
      - name: Runner upgrades
        run: |
          omz update
          brew upgrade
